<body>  
  <div class="container">               
    <div class="row">
      <!-- Page header -->
      <div class="col-md-4">
     
      </div>                
    </div>
    <div class="row">
      <div class="col-md-12">
          <h1>Welcome to Vehicle Online Store.</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <!-- Breadcrumbs -->        
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <!-- Page content placeholder -->
        <?= $this->content; ?>
      </div>
    </div>
   <!-- /container -->
  <?php echo $this->inlineScript() ?>
</body>