<?php $this->headTitle('Add review'); ?>
<body>

    <div class="container">
        <h2>Welcome to Vehicle Ishop</h2>
        <form class="form-horizontal reviewForm" action="<?= $this->url('application', ['action' => 'review-form', 'id' => $vid]); ?>" method="post">


            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Review Title:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="user-email" name="rTitle">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="comment">Comment:</label>
                <div class="col-sm-10">
                <textarea class="form-control" rows="5" id="comment" name="rBody"></textarea>
                </div>
            </div>
         
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Add Review</button>
                </div>
            </div>
        </form>



</body>