
<?php $this->headTitle("Search Vehicle") ?>

<body>

    <div class="container maincontainer">
        <p class="vs-label">Vehicle Store</p>
        <h2>Welcome to vehicle store.</h2>
        <form class="form-horizontal searchForm" action="/application/searchResult" method="get">
            <p class="que-tit">What Are You Looking For?</p>
           
            <div class="form-group">
                <label class="control-label col-sm-2 " for="vtype">Vehicle Type:</label>
                <div class="col-sm-10">
                    <select id="vtype" class="form-control" name="vtype">
                        <?php
                        foreach ($types as $key => $val) {
                            ?>
                            <option ><?php echo $val->getTitle(); ?></option>
                            <?php
                        }
                        ?>
                    </select>
                    <!--input type="email" class="form-control" id="email" placeholder="Enter email"-->
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Min Budget:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="min-budget" name="minbudget" style="border: 1px solid lightgray;">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" >Max Budget:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="max-budget" name="maxbudget" style="border: 1px solid lightgray;">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" >Keywords:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="keyword" name="keyword" placeholder="Enter Keywords">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Search</button>
                </div>
            </div>
        </form>
        <div class="row mainphoto">
            <img src="<?php echo $this->basepath('img/vehicleImages/main2.jpg'); ?>" width="626" height="336">
        </div>


</body>