<?= $this->headTitle('Vehicle Detail'); ?>

<script src="<?php echo $this->basepath('js/sliderScript.js'); ?>"></script>
<body>
    <div class="container">
        <header class="head-d">
            <div class="row">
                <div class="col-md-9 col-sm-7 col-xs-12 header-title">Vehicle Store</div>
            </div>
        </header>
        <div class="row detail-panel">
            <div class="row title">
                <div class="col-md-10 col-sm-7 col-xs-12"><p class="price"><span><?php echo $vehicle->getMake(); ?> - <?php echo $vehicle->getModel(); ?> - <?php echo $vehicle->getYear(); ?></span></p></div>
                <div class="col-md-2 col-sm-5 hidden-xs"><p class="price"><span id="lblDetailPrice">$ <?php echo $vehicle->getPrice(); ?></span></p></div>
            </div>

            <div class="row body">


                <!-- Top part of the slider -->
                <div class="row">
                    <div class="col-sm-7" id="carousel-bounding-box">
                        <div class="carousel slide" id="myCarousel" data-interval="false">
                            <!-- Carousel items -->
                            <div class="carousel-inner">

                                <?php foreach ($vehicle->getImages() as $key => $image):
                                    ?>
                                    <div class="item <?php echo $key == 0 ? 'active' : ''; ?>" data-slide-number="<?php echo $key ?> ">
                                        <img src="<?php echo $this->basepath('img/vehicleImages/') . $image->getImagepath() . '.jpg'; ?>" >
                                    </div>
                                    <?php
                                endforeach;
                                ?>
                            </div><!-- Carousel nav -->
                            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>                                       
                            </a>
                            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>                                       
                            </a>                                
                        </div>
                    </div>
                    <div class="col-sm-5 vehicle-details">
                        <span class="detail-title">Sell by:</span>
                        <span><?php echo $vehicle->getSeller()->getType(); ?></span>
                        </br>
                        <span class="detail-title">Seller Name:</span>
                        <span><?php echo $vehicle->getSeller()->getName(); ?></span>
                        </br>
                        <span class="detail-title">Address:</span>
                        <span><?php echo $vehicle->getSeller()->getAddress(); ?></span>
                        </br>
                        <span class="detail-title">Phone #:</span>
                        <span><?php echo $vehicle->getSeller()->getPhone(); ?></span>
                        </br>
                        <span class="detail-title">website:</span>
                        <span><?php echo $vehicle->getSeller()->getWebsite(); ?></span>
                        </br>
                        <span style="margin-right: 10px;">
                            <a href="<?php echo $this->url('application', array('action' => 'mailForm', 'id' => $vehicle->getId())); ?>">
                                <button class="btn btn-warning"><i class="glyphicon glyphicon-envelope"></i> Email seller</button>
                            </a>
                        </span>
                        <span><a href="<?php echo $this->url('application', array('action' => 'reviewForm', 'id' => $vehicle->getId())); ?>">
                                <button class="btn btn-info"><i class="glyphicon glyphicon-send"></i> Add Review</button></a></span>
                    </div>

                </div>
            </div>

            <div class="row hidden-xs" id="slider-thumbs">
                <!-- Bottom switcher of slider -->
                <ul class="hide-bullets" style="list-style-type: none;">
                    <?php foreach ($vehicle->getImages() as $key => $image):
                        ?>
                        <li class="col-sm-2">
                            <a class="thumbnail" id="carousel-selector-<?= $key ?>">
                                <img src="<?php echo $this->basepath('img/vehicleImages/') . $image->getImagepath() . '.jpg'; ?>" >
                            </a>
                        </li>
                        <?php
                    endforeach;
                    ?>
                </ul>                 
            </div>
        </div>
        <div class="row">
            <div id="reviews-container">
                <h2>Reviews: </h2>
                <?php foreach ($vehicleReviews as $key => $review):
                    ?>
                    <div class="review-div">
                        <h4 style="color: darkred; font-family: fantasy;"><?php echo $review->getTitle(); ?></h4></br>
                        <p><?php echo $review->getBody(); ?></p>
                    </div>
                    <?php
                endforeach;
                ?>
            </div>
        </div>
    </div>
</body>