

<head>
    <title>Search Vehicle</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .photos, .trending-photos {
            padding-bottom: 20px;
            clear: both;
        }
        .photo-item {
            float: left;
            margin-bottom: 5px;
            position: relative;
        }
        .searchForm{
            border:1px solid lightgray;
            margin-bottom: 3%;
            padding: 1%;
            width:50%;
        }
    </style>
</head>
<body>

    <div class="container">
        <h2>Welcome to Vehicle Ishop</h2>
        <form class="form-horizontal searchForm" action="/application/searchResult" method="get">
            <div class="form-group">
                <label class="control-label col-sm-2" for="vtype">Vehicle Type:</label>
                <div class="col-sm-10">
                    <select id="vtype" class="form-control" name="vtype">
                        <?php
                        foreach ($types as $key => $val) {
                            ?>
                            <option ><?php echo $val->getTitle(); ?></option>
                            <?php
                        }
                        ?>
                    </select>
                    <!--input type="email" class="form-control" id="email" placeholder="Enter email"-->
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Min Budget:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="min-budget" name="minbudget" style="border: 1px solid lightgray; color:red; font-weight:bold;">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" >Max Budget:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="max-budget" name="maxbudget" style="border: 1px solid lightgray; color:red; font-weight:bold;">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" >Keywords:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="keyword" name="keyword" placeholder="Enter Keywords">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Search</button>
                </div>
            </div>
        </form>

    

</body>